name: Verify PR

on:
    pull_request:
        branches: [main]

jobs:
    verify-pr:
        timeout-minutes: 3
        runs-on: ubuntu-latest
        permissions:
            contents: read
        container:
            image: mcr.microsoft.com/playwright:v1.56.1-noble
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: '22.x'
            - name: Install dependencies
              run: npm ci
            - name: Prettier
              run: npm run pretty-check
            - name: ESLint
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Run Playwright tests
              run: npx playwright test
            - name: Upload playwright report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 1
